# ------------------------------------------------------------------------------
# Build.yml
# ------------------------------------------------------------------------------

name: Build

on:
  push:
  pull_request:
    branches-ignore:
      - master
      - main
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: windows-latest
    env:
      RICAUN_REVITTEST_TESTADAPTER_NUNIT_APPLICATION: ${{ secrets.RICAUN_REVITTEST_DA_APPLICATION }}
      APS_CLIENT_ID: ${{ secrets.APS_CLIENT_ID }}
      APS_CLIENT_SECRET: ${{ secrets.APS_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v1
      - name: Run './build/build.cmd'
        run: ./build/build.cmd --root ./build
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            **/*.trx
